export type ActionTypes =
  | "CONNECTION_CHANGE"
  | "CONNECTION_START_LISTENING"
  | "CONNECTION_STOP_LISTENING";

export const actions: { [key in ActionTypes]: ActionTypes } = {
  CONNECTION_CHANGE: "CONNECTION_CHANGE",
  CONNECTION_START_LISTENING: "CONNECTION_START_LISTENING",
  CONNECTION_STOP_LISTENING: "CONNECTION_STOP_LISTENING",
};
