export type ActionTypes =
  | "CHANGE_PASSWORD"
  | "CHANGE_USERNAME"
  | "CHANGE_EMAIL"
  | "ON_PRESS_SIGNUP"
  | "ON_PRESS_SIGNIN"
  | "ON_PRESS_TERMS";

export const actions: { [key in ActionTypes]: ActionTypes } = {
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_USERNAME: "CHANGE_USERNAME",
  CHANGE_EMAIL: "CHANGE_EMAIL",
  ON_PRESS_SIGNIN: "ON_PRESS_SIGNIN",
  ON_PRESS_SIGNUP: "ON_PRESS_SIGNUP",
  ON_PRESS_TERMS: "ON_PRESS_TERMS"
};
