export type ActionTypes =
  | "TOGGLE_TRACKING"
  | "RECEIVED_USER_ID"
  | "RECEIVED_SAGA_ID"
  | "RECEIVED_CHAPTER_ID"
  | "REQUEST_SAGA_BEGIN"
  | "REQUEST_SAGA_STOP"
  | "REQUEST_SAGA";

export const actions: { [key in ActionTypes]: ActionTypes } = {
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_USERNAME: "CHANGE_USERNAME",
  CHANGE_EMAIL: "CHANGE_EMAIL",
  ON_PICK_DATE: "ON_PICK_DATE",
  HIDE_DATE_PICKER_MODAL: "HIDE_DATE_PICKER_MODAL",
  ON_PRESS_SIGNIN: "ON_PRESS_SIGNIN",
  ON_PRESS_SIGNUP: "ON_PRESS_SIGNUP",
  ON_PRESS_TERMS: "ON_PRESS_TERMS",
  SHOW_DATE_PICKER_MODAL: "SHOW_DATE_PICKER_MODAL"
};
