export type ActionTypes =
  | "TOGGLE_TRACKING"
  | "RECEIVED_USER_ID"
  | "RECEIVED_SAGA_ID"
  | "RECEIVED_CHAPTER_ID"
  | "REQUEST_SAGA_BEGIN"
  | "REQUEST_SAGA_STOP"
  | "REQUEST_SAGA";

export const actions: { [key in ActionTypes]: ActionTypes } = {
  TOGGLE_TRACKING: "TOGGLE_TRACKING",
  RECEIVED_USER_ID: "RECEIVED_USER_ID",
  RECEIVED_SAGA_ID: "RECEIVED_SAGA_ID",
  RECEIVED_CHAPTER_ID: "RECEIVED_CHAPTER_ID",
  REQUEST_SAGA_BEGIN: "REQUEST_SAGA_BEGIN",
  REQUEST_SAGA_STOP: "REQUEST_SAGA_STOP",
  REQUEST_SAGA: "REQUEST_SAGA"
};
